[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://gasflow-backend.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200